syntax on
colorscheme SpaceDark

set number


"Go Synatx Highlighting
let g:go_highlight_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_operators = 1
let g:go_highlight_extra_types = 1

"Plugins
 let g:rainbow_active = 1 "set to 0 if you want to enable it later via :RainbowToggle

