syntax on
colorscheme SpaceDark
filetype plugin indent on


set number

"Set tabs to 4 spaces
set tabstop=4       " The width of a TAB is set to 4.
set shiftwidth=4    " Indents will have a width of 4.
set softtabstop=4   " Sets the number of columns for a TAB.
set expandtab       " Expand TABs to spaces.

"Go Synatx Highlighting
let g:go_highlight_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_operators = 1
let g:go_highlight_extra_types = 1

"Plugins
 let g:rainbow_active = 1 "set to 0 if you want to enable it later via :RainbowToggle

 let g:terraform_fmt_on_save=1 "Allow vim-terraform to automatically format *.tf and *.tfvars files with terraform fmt

